package com.rra.tracker.model.slave;
// Generated 16 Jul, 2021 11:23:31 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

/**
 * SampleWs generated by hbm2java
 */
@Entity
@Table(name="SAMPLE_WS"
)
public class SampleWs  implements java.io.Serializable {


     private int id;
     private int jobID;
     private int fileStatus;
     private String filename;
     private byte[] zipFile;
     private byte[] pcnList;
     private byte[] signature;

    public SampleWs() {
    }

	
    public SampleWs(int id) {
        this.id = id;
    }
    public SampleWs(int id, byte[] zipFile) {
       this.id = id;
       this.zipFile = zipFile;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Column(name="zip_file")
    public byte[] getZipFile() {
        return this.zipFile;
    }
    
    public void setZipFile(byte[] zipFile) {
        this.zipFile = zipFile;
    }

    /**
     * @return the jobID
     */
    @Column(name="JOB_ID")
    public int getJobID() {
        return jobID;
    }

    /**
     * @param jobID the jobID to set
     */
    public void setJobID(int jobID) {
        this.jobID = jobID;
    }

    /**
     * @return the filename
     */
    @Column(name="FILENAME")
    public String getFilename() {
        return filename;
    }

    /**
     * @param filename the filename to set
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * @return the fileStatus
     */
    @Column(name="FILESTATUS")
    public int getFileStatus() {
        return fileStatus;
    }

    /**
     * @param fileStatus the fileStatus to set
     */
    public void setFileStatus(int fileStatus) {
        this.fileStatus = fileStatus;
    }

    @Column(name="pcnlist")
    public byte[] getPcnList() {
        return pcnList;
    }

    public void setPcnList(byte[] pcnList) {
        this.pcnList = pcnList;
    }
    @Column(name="signature")
    public byte[] getSignature() {
        return signature;
    }

    public void setSignature(byte[] signature) {
        this.signature = signature;
    }
}


