server.port=9199

#spring.datasource.url= jdbc:postgresql://192.168.1.57:5432/msp
spring.datasource.url= jdbc:postgresql://61.95.183.14:5432/msp
spring.datasource.username= postgres
spring.datasource.password= YJEJZbXMMbiDWSEconeCnA



spring.second.datasource.url=jdbc:postgresql://10.10.10.171:5432/psa_print
spring.second.datasource.username=psaprint
spring.second.datasource.password=psaprint@#213
#spring.second.datasource.url=jdbc:postgresql://openshift-staging-db.co3nrmiboa1o.ap-southeast-1.rds.amazonaws.com:5432/psa_print
#spring.second.datasource.username=postgres
#spring.second.datasource.password=QszJ3UZN2ZiVFDYoMP8A


#
#spring.aws.datasource.url= jdbc:postgresql://openshift-staging-db.co3nrmiboa1o.ap-southeast-1.rds.amazonaws.com:5432/msp
#spring.aws.datasource.username= postgres
#spring.aws.datasource.password= QszJ3UZN2ZiVFDYoMP8A

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.connection.driver_class.= org.postgresql.Driver
spring.jpa.hibernate.ddl-auto= none
spring.jpa.show-sql=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration