server.port=9199
spring.datasource.url= jdbc:sqlserver://10.10.10.52:1433;databaseName=punjab_test
spring.datasource.username= sa
spring.datasource.password= dbadm!N#18
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto= none